# Generated by Django 5.1.7 on 2025-03-22 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('politics', 'Politics'), ('style', 'Style'), ('science', 'Science'), ('technology', 'Technology'), ('culture', 'Culture'), ('business', 'Business'), ('fashion', 'Fashion'), ('environment', 'Environment'), ('travel', 'Travel'), ('health', 'Health')], default='general', max_length=50),
        ),
    ]
